services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
      
  json-server:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    volumes:
      - ./src/db:/app/src/db
    command: ["npm", "run", "json-server"]
    networks:
      - app-network
  
  dbgate:
    image: dbgate/dbgate
    ports:
      - 4050:3000
    volumes:
      - dbgate-data:/root/.dbgate
    depends_on:
      - postgres
    environment:
      CONNECTIONS: con1

      LABEL_con1: Postgres
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: postgres
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
  dbgate-data:

networks:
  app-network:
    driver: bridge
